# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{purple_ruby}
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Xue Yong Zhi", "Pradeep Elankumaran", "Davide D'Agostino", "Pavel Valodzka", "Greg Hazel"]
  s.date = %q{2010-04-02}
  s.description = %q{A ruby gem to write server that sends and recives IM messages}
  s.email = %q{}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "examples/purplegw_example.rb",
     "ext/account.c",
     "ext/extconf.rb",
     "ext/purple_ruby.c",
     "ext/reconnect.c",
     "lib/purple_ruby.rb"
  ]
  s.homepage = %q{http://github.com/valodzka/purple_ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A ruby gem to write server that sends and recives IM messages}
  s.test_files = [
    "examples/purplegw_example.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

